### ISSUE TITLE
a few links to update

### ISSUE THREAD

**Issue by PatrickTague** [jsommers/cbook#6]
* Chapter 1, footnote [2] --> current link is broken, change to https://www.tiobe.com/tiobe-index/
* Chapter 3, footnote [3] --> current link redirects, so it works, but maybe update to https://ai.googleblog.com/2006/06/extra-extra-read-all-about-it-nearly.html in case the redirect goes away
* Chapter 7, footnotes [2] and [5] have a needed ')' outside of the link

**Comment by jsommers** [comment]
Thanks for those comments and fixes!
